joy_node:
  ros__parameters:
  device_id: 0
  deadzone: 0.05
  autorepeat_rate: 20.0



teleop_node:
  ros__parameters:
    # The name of the node
    node_name: teleop_twist_joy
    # The name of the topic to publish to
    topic_name: cmd_vel
    # The name of the topic to subscribe to
    enable_button: 7

    axis_linear: 1
    scale_linear: 0.5

    axis_angular: 2
    scale_angular: 0.5
